---
abstract: 'Fast JSON::XS handler for Mojolicious::Renderer'
author:
  - 'yowcow <yowcow@cpan.org>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.7.2, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MojoX-Renderer-JSON-XS
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  MojoX::Renderer::JSON::XS:
    file: lib/MojoX/Renderer/JSON/XS.pm
    version: 0.01
  Mojolicious::Plugin::JSON::XS:
    file: lib/Mojolicious/Plugin/JSON/XS.pm
requires:
  JSON::XS: 0
  Mojolicious: 0
  parent: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/yowcow/MojoX-Renderer-JSON-XS/issues
  homepage: https://github.com/yowcow/MojoX-Renderer-JSON-XS
  repository: git://github.com/yowcow/MojoX-Renderer-JSON-XS.git
version: 0.01
